name: Manual

on:
  workflow_dispatch:
    inputs:
      build_container:
        description: 'Build Container'
        required: true
        type: boolean
      build_version:
        description: 'Build Version Number'
        default: 'latest'
      environment:
        default: 'prod'


jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "![](https://www.pknw1.co.uk/assets/img/pknw1logo-white.png)"  >> $GITHUB_STEP_SUMMARY
          echo "${{ github.fullName }} " >> $GITHUB_STEP_SUMMARY
          TIMESTAMP=$(date +%s)
          echo ${TIMESTAMP} >> $GITHUB_STEP_SUMMARY
          echo "started at "${TIMESTAMP}  >> $GITHUB_STEP_SUMMARY
          echo " - [X] update docker-compose.yml"  >> $GITHUB_STEP_SUMMARY
          echo " - [X] image  ${{ inputs.build_version }} " >> $GITHUB_STEP_SUMMARY
          echo " - [X] image  ${{ inputs.build_version }} " >> $GITHUB_STEP_SUMMARY
