name: Manual

on:
  workflow_dispatch:
    inputs:
      build_container:
        description: 'Build Container'
        required: true
        type: boolean
      build_version:
        description: 'Build Version Number'
        default: 'latest'
      environment:
        default: 'prod'


jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "![](https://www.pknw1.co.uk/assets/img/pknw1logo-white.png =100xx70)"  >> $GITHUB_STEP_SUMMARY
          echo "::set-output name=content::$SUMMARY_HEADER"
          echo "$SUMMARY_HEADER" >> $GITHUB_STEP_SUMMARY
