name: Manual

on:
  workflow_dispatch:
    inputs:
      build_container:
        description: 'Build Container'
        required: true
        type: boolean
      build_version:
        description: 'Build Version Number'
        default: 'latest'
      environment:
        default: 'prod'


jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          SUMMARY_HEADER=$(cat << EOF
          first line
          second line
          third line
          EOF
          )
          echo "::set-output name=content::$SUMMARY_HEADER"
          echo "$SUMMARY_HEADER" >> >> $GITHUB_STEP_SUMMARY
